;;------------------  ASM30 API for PI routines ---------------------
; PIParm stucture:
;
        .equ PI_qdSumL,0    
        .equ PI_qdSumH,2    
        .equ PI_qKp,4      
        .equ PI_qKi,6      
        .equ PI_qKc,8      
        .equ PI_qOutMax,10 
        .equ PI_qOutMin,12 
        .equ PI_qInRef,14  
        .equ PI_qInMeas,16 
        .equ PI_qOut,18    
        
        .equ NKo,4

